### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mmore500** [mmore500/outset#17]
- [x] rewrite docs
- [x] move content to integration examples
- [x] make singleton OutsetGrid fall back to magnifying glass icon
- [x] add example of split by hue, column, and outset
- [x] add an example disabling column/hue
- [x] make a taxonomy graphic
- [x] turn everything into functors
- [x] write docstrings for resize_clip_outliers
- [x] test resize_clip_outliers
- [x] add source/outset kwargs
- [x] add stretch_unit
- [x] make default stretch nonzero for small outsets
- [x] make default marker size proportional to axis size
- [x] expose `make_corner_insets` publicly and document it in `inset_outsets`

**Comment by mmore500** [comment]
- [ ] fix stubbed value tests

**Comment by mmore500** [comment]
- [ ] add marker wiggle

**Comment by mmore500** [comment]
- [ ] fix axis scaling

**Comment by mmore500** [comment]
- [ ] standardize raw frame format to outsetgrid

**Comment by mmore500** [comment]
- [ ] fix ticker in singleton example

**Comment by mmore500** [comment]
- [ ] fix huefull squish

**Comment by mmore500** [comment]
- [ ] fix axis scaling for manual frames
